name: DevSecOps CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "*/15 * * * *"   # every 15 min (polling, like Jenkins scheduled poll)

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          mkdir -p logs
          npm test || true | tee logs/tests.log

      - name: Generate coverage report
        run: |
          npm run coverage || true
          if [ -f coverage/lcov.info ]; then echo "Coverage report generated"; else echo "No coverage found"; fi

      - name: NPM Audit (Security Scan)
        run: |
          npm audit || true | tee logs/npm-audit.log

      - name: Upload logs and coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: |
            logs/**
            coverage/**

  sonarcloud:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Download coverage from CI job
        uses: actions/download-artifact@v4
        with:
          name: ci-logs
          path: .

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          projectBaseDir: .
"# test change" 
